palette = "catppuccin_mocha"
add_newline = false

[palettes.catppuccin_mocha]
rosewater = "#F5E0DC"
flamingo = "#F2CDCD"
pink = "#F5C2E7"
mauve = "#CBA6F7"
red = "#F38BA8"
maroon = "#EBA0AC"
peach = "#FAB387"
yellow = "#F9E2AF"
green = "#A6E3A1"
teal = "#94E2D5"
sky = "#89DCEB"
sapphire = "#74C7EC"
blue = "#89B4FA"
lavender = "#B4BEFE"
text = "#CDD6F4"
subtext1 = "#BAC2DE"
surface0 = "#313244"
base = "#1E1E2E"

format = "$directory$git_branch$git_status$character"

[directory]
style = "bold fg:blue"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "fg:mauve"
format = "[$symbol$branch]($style) "
truncation_length = 24

[git_status]
style = "fg:subtext1"
format = "[$all_status$ahead_behind]($style) "
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${ahead_count}/${behind_count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
deleted = "✕${count}"
renamed = "»${count}"

[character]
success_symbol = "[❯](fg:green)"
error_symbol = "[❯](fg:red)"
vimcmd_symbol = "[❮](fg:blue)"

[aws]
disabled = true

[gcloud]
disabled = true
